---
- name: Instalar MariaDB en server02
  hosts: dbserver
  become: true
  vars:
    db_root_password: "tlxadmin"
    db_user: "sysadmin"
    db_user_password: "tlxadmin"
    db_name: "DatabaseTSL"
  tasks:
    - name: Instalar MariaDB
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: true

    - name: Iniciar y habilitar el servicio de MariaDB
      ansible.builtin.systemd_service:
        name: mariadb
        state: started
        enabled: true

    - name: Asegurar MariaDB con mysql_secure_installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter current password for root (enter for none):': ''
          'Set root password? \[Y/n\]': 'Y'
          'New password:': "{{ db_root_password }}"
          'Re-enter new password:': "{{ db_root_password }}"
          'Remove anonymous users? \[Y/n\]': 'Y'
          'Disallow root login remotely? \[Y/n\]': 'Y'
          'Remove test database and access to it? \[Y/n\]': 'Y'
          'Reload privilege tables now? \[Y/n\]': 'Y'

    - name: Crear base de datos
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Crear usuario de base de datos
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: "{{ DatabaseTSL }}.*:ALL"
        host: "%"
        state: present

    - name: Configurar el firewall para MariaDB
      community.general.ufw:
        rule: allow
        name: 'MySQL'
        port: '3306'
        proto: tcp
