---
- name: Configurar base de datos MySQL
  hosts: database
  become: true
  user: sysadmin
  tasks:
    - name: Crear el usuario root y otorgar permisos
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' -e "CREATE USER 'root'@'%' IDENTIFIED BY '{{ db_root_password }}';"
        mysql -u root -p'{{ db_root_password }}' -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
        mysql -u root -p'{{ db_root_password }}' -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: "{{ db_root_password }}"
      vars:
        db_root_password: "tlxadmin"

    - name: Crear base de datos todo
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' -e "CREATE DATABASE IF NOT EXISTS todo;"
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: "{{ db_root_password }}"
      vars:
        db_root_password: "tlxadmin"

    - name: Copiar archivo SQL al servidor
      ansible.builtin.copy:
        src: ./Files/todo.sql
        dest: /tmp/todo.sql

    - name: Importar archivo SQL
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' todo < /tmp/todo.sql
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: "{{ db_root_password }}"
      vars:
        db_root_password: "tlxadmin"

## Creo usuarios y los muestro al final para verificar:

    - name: Agregar usuarios de prueba a la base de datos
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' -e "
        USE todo;
        INSERT INTO users (first_name, last_name, username, password) VALUES ('Pepe', 'Momo', 'pmomo', 'password1');
        INSERT INTO users (first_name, last_name, username, password) VALUES ('Tita', 'Merelo', 'tmerelo', 'password2');
        INSERT INTO users (first_name, last_name, username, password) VALUES ('Tito', 'Perez', 'tperez', 'password3');
        "
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: "{{ db_root_password }}"
      vars:
        db_root_password: "tlxadmin"

    - name: Consultar y mostrar los usuarios creados
      ansible.builtin.shell: |
        mysql -u root -p'{{ db_root_password }}' -e "
        USE todo;
        SELECT * FROM users;
        "
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: "{{ db_root_password }}"
      register: query_result
      vars:
        db_root_password: "tlxadmin"

    - name: Mostrar resultado de la consulta
      ansible.builtin.debug:
        var: query_result.stdout
