[centos]
webserver01   ansible_host=192.168.56.102

[ubuntu]
dbserver    ansible_host=192.168.56.104

[database]
dbserver    ansible_host=192.168.56.104

[webserver]
webserver01   ansible_host=192.168.56.102

[webservers:vars]
admin_user=sysadmin
admin_pass=tlxadmin

[linux:children]
centos
ubuntu