[centos]
webserver01    ansible_host=192.168.56.105

[ubuntu]
dbserver    ansible_host=192.168.56.104

[debian]
webserver_debian    ansible_host=192.168.56.108

[database]
dbserver    ansible_host=192.168.56.104

[webserver]
webserver01   ansible_host=192.168.56.105

[linux:children]
centos
ubuntu
debian
