[centos]
webserver01   ansible_host=192.168.56.103

[ubuntu]
dbserver    ansible_host=192.168.56.104

[database]
dbserver    ansible_host=192.168.56.104

[webserver]
webserver01   ansible_host=192.168.56.103

[linux:children]
centos
ubuntu