[centos]
webserver   ansible_host=192.168.56.40

[ubuntu]
dbserver    ansible_host=192.168.56.104

[database]
dbserver    ansible_host=192.168.56.104

[webserver]
webserver   ansible_host=192.168.56.40

[linux:children]
centos
ubuntu